### ISSUE TITLE
Does not compile with gcc 4.6.2

### ISSUE THREAD

**Issue by vadim-skorba** [vkholodkov/nginx-eval-module#9]
Hi, Valery

I've tried to compile other nginx versions (1.0.11 - 1.1.15) on server with gcc 4.6.2 with last (https://github.com/vkholodkov/nginx-eval-module/commit/125fa2e97399d29ce148f55cc6975268e482d212) version of that module and it was failed with such errors:

> ../nginx-eval-module/ngx_http_eval_module.c: In function ‘ngx_http_eval_block’:
> ../nginx-eval-module/ngx_http_eval_module.c:640:39: error: variable ‘pclcf’ set but not used [-Werror=unused-but-set-variable]
> ../nginx-eval-module/ngx_http_eval_module.c:631:32: error: variable ‘ecf’ set but not used [-Werror=unused-but-set-variable]
> The problem is - new gcc becomes smarter and for now unused variables throws warnings. Nginx default config is:
> -Werror=unused-but-set-variable]
> So, it would be great to fix module instead of changing nginx default options.

Thank you!
Vadim.
